### ISSUE TITLE
Standup Dockerized Open Telemetry Developent Stack

### ISSUE THREAD

**Issue by kMaiSmith** [Jeffercodians/MOTel#4]
- [x] docker-compose.yaml stands up services for development stack
  - [x] yaeger
  - [x] minecraft forge
- [x] environment configurations is read from users .env file

**Comment by folkengine** [comment]
By the power of me, the Great and Powerful Christoph, hand of Jeff, I hereby bless this issue as being closed.

**Comment by folkengine** [comment]
By the power of me, the Great and Powerful Christoph, hand of Jeff, I hereby bless this issue as being closed. Hail, Jeff!
